### ISSUE TITLE
Need to configure custom domain

### ISSUE THREAD

**Issue by adhityav** [yoja-ai/yoja-ai.github.io#1]
We need to set up DNS entries for yoja.ai for this site.

**Comment by jagane** [comment]
DNS for yoja.ai is hosted at Amazon Route 53. It appears that you cannot create a CNAME entry for all of the domain, i.e. yoja.ai to point to https://yoja-ai.github.io. Therefore, I created a redirect index.html and placed it in our current hosting location. The effect is the same - if you point your browser at https://yoja.ai you will be taken to https://yoja-ai.github.io
